config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'post/:id/likes', to: 'posts#likes', as: :likes
  get 'post/:id/unlikes', to: 'posts#unlikes', as: :unlikes
  get 'post/:id/togglelikes', to: 'posts#togglelikes', as: :togglelikes
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like

  
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_likeable
  acts_as_liker

  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    acts_as_follower
    acts_as_followable
    acts_as_likeable
    acts_as_liker

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def likes
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @post = Post.find(params[:id])
    @user.like!(@post)
    redirect_to :back, notice: "Liked this post successfully"
  end

  def unlikes
    @user = current_user # before_action :authenticate_user, only: [:likes]
    @post = Post.find(params[:id])
    @user.unlike!(@post)
    redirect_to :back, notice: "Unliked this post successfully!"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id if current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :user_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/nav' %>
    <div class="container">
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav>
    <div class="nav-wrapper">
        <%= link_to "INSTA", root_path, class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
                        <li><%= link_to 'New Post', new_post_path %></li>
            <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
        <% else %>
            <li>
                <%= link_to('Login', new_user_session_path)  %>
            </li>
            <% end %>
            <% if user_signed_in? %>
            <li>
                <%= link_to('Edit registration', edit_user_registration_path) %>
            </li>
        <% else %>
            <li>
                <%= link_to('Register', new_user_registration_path)  %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/posts/_form.html.erb
<%= form_for post,  html: { multipart: true } do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

</br></br>
    <% @posts.each do |post| %>
    <div class="row">
      <div class="col l8 offset-l2">
        <div class="card">
          <div class="card-action">
              <span class="card-title"><%= post.user.email %></span>
            </div>
          <div class="card-image">
            <%= image_tag post.image %>
          </div>
          <div class="card-content">
            <p class="left-align" style="font-weight:bold">Likes:  <span style="font-weight:lighter"><%= post.likers(User).count %></span></p>

            <p class="left-align" style="font-weight:bold">Likers: <span style="font-weight:lighter"> <% post.likers(User).count do |likers| %>,
            <%= likers.email %><% end %></span></p>
          </br>
            <p class="description"><%= post.description %></p>
          </div>
          <div class="card-action">
            <% if user_signed_in? %>
            <% if current_user.likes?(post) %>
            <%= link_to '<i class="fa fa-heart fa-3x"></i>'.html_safe, unlikes_path(post) %>
            <% elsif %>
            <%= link_to '<i class="fa fa-heart-o fa-3x"></i>'.html_safe, likes_path(post) %>
            <% end %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

  <% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <%= image_tag @post.image.url(:medium) %>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>